### ISSUE TITLE
视频下载失败：JSONObject["quality"] not found

### ISSUE THREAD

**Issue by DreamerDK** [nICEnnnnnnnLee/BilibiliDown#177]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
下载某些视频时会失败，无法获取下载链接。

**相关信息**
+ 当前系统(windows/linux等)：windows 11
+ java版本：java11、java17、自带jre的版本都试过
+ 相关链接或者BV号：BV1et411b73Z
+ 账号是否登录：已登录
+ 在网页端观看是否存在问题：没有问题
+ 是否存在自定义parsers：没有
+ 相关log
```java
MJTab label的点击事件
你点击了一次下载按钮...
查询记录BV1et411b73Z-80-p1
已经下载过 BV1et411b73Z-80-p1
你点击了一次下载按钮...
查询记录BV1et411b73Z-80-p2
匹配BVParser: BV1et411b73Z
InputParser-selectParser/66 : BV1et411b73Z
匹配BVParser: BV1et411b73Z
正在查询MP4/FLV链接...
API-getWbiUrl/109 : https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png
API-getWbiUrl/113 : https://i0.hdslb.com/bfs/wbi/4932caff0ff746eab6f01bf08b70ac45.png
API-getWbiUrl/115 : 7cd084941338484aae1ad9425b84077c4932caff0ff746eab6f01bf08b70ac45
AbstractBaseParser-getVideoLinkByFormat/312 : https://api.bilibili.com/x/player/wbi/playurl?cid=1233403794&bvid=BV1et411b73Z&qn=80&type=&otype=json&fnver=0&fnval=4048&fourk=1&w_rid=d79004381caa789f9f5dc99c1948dd09&wts=1703397554
{"code":0,"message":"0","ttl":1,"data":{"v_voucher":"voucher_7758a05f-7b6f-4fa2-87e5-bd9030145c49"}}

Exception in thread "pool-1-thread-1" 你点击了一次下载按钮...
org.json.JSONException: JSONObject["quality"] not found.
查询记录BV1et411b73Z-80-p3
        at org.json.JSONObject.get(JSONObject.java:580)
        at org.json.JSONObject.getNumber(JSONObject.java:719)
        at org.json.JSONObject.getInt(JSONObject.java:742)
        at nicelee.bilibili.parsers.impl.AbstractBaseParser.getVideoLinkByFormat(AbstractBaseParser.java:328)
        at nicelee.bilibili.parsers.impl.AbstractBaseParser.getVideoLink(AbstractBaseParser.java:231)
        at nicelee.bilibili.parsers.InputParser.getVideoLink(InputParser.java:121)
        at nicelee.ui.thread.DownloadRunnable.download(DownloadRunnable.java:91)
        at nicelee.ui.thread.DownloadRunnable.run(DownloadRunnable.java:60)
匹配BVParser: BV1et411b73Z
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
InputParser-selectParser/66 : BV1et411b73Z
匹配BVParser: BV1et411b73Z
正在查询MP4/FLV链接...
AbstractBaseParser-getVideoLinkByFormat/312 : https://api.bilibili.com/x/player/wbi/playurl?cid=1233403922&bvid=BV1et411b73Z&qn=80&type=&otype=json&fnver=0&fnval=4048&fourk=1&w_rid=6eb59eee9b09bfb4ce50c887707c47d1&wts=1703397554
{"code":0,"message":"0","ttl":1,"data":{"v_voucher":"voucher_a11d5a1d-5374-43f5-a77d-779c457bc0dc"}}

Exception in thread "pool-1-thread-2" org.json.JSONException: JSONObject["quality"] not found.
        at org.json.JSONObject.get(JSONObject.java:580)
你点击了一次下载按钮...
        at org.json.JSONObject.getNumber(JSONObject.java:719)
查询记录BV1et411b73Z-80-p4
        at org.json.JSONObject.getInt(JSONObject.java:742)
        at nicelee.bilibili.parsers.impl.AbstractBaseParser.getVideoLinkByFormat(AbstractBaseParser.java:328)
        at nicelee.bilibili.parsers.impl.AbstractBaseParser.getVideoLink(AbstractBaseParser.java:231)
        at nicelee.bilibili.parsers.InputParser.getVideoLink(InputParser.java:121)
        at nicelee.ui.thread.DownloadRunnable.download(DownloadRunnable.java:91)
        at nicelee.ui.thread.DownloadRunnable.run(DownloadRunnable.java:60)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
匹配BVParser: BV1et411b73Z
        at java.base/java.lang.Thread.run(Thread.java:833)
```

```
请在发表issue前进行预览，将影响排版的内容放到这里
```

**Comment by nICEnnnnnnnLee** [comment]
这是被风控了导致返回的内容不符预期。     


这里可以列举一些可能预防或者解决问题的方案，但并不一定有效。  
+ 退出登录，并删除config文件夹下的`fingerprint.config`，在后续动作完毕后重启程序并重新登录
+ 打开配置页，搜索并修改`bilibili.userAgent.pc`为你常用浏览器的值
+ 将查询、下载等间隔适当放大，比如将下列配置项设为`5000`
  ```
  bilibili.download.period.between.download
  bilibili.download.period.between.query
  ```

**Comment by DreamerDK** [comment]
以上方法使用后无效，但更换网络环境后无此问题，应该是那个使用的宽带被风控了。
