### ISSUE TITLE
视频无法列出列表

### ISSUE THREAD

**Issue by HanakoLuna** [nICEnnnnnnnLee/BilibiliDown#49]
部分log：
`AbstractBaseParser-getAVDetail/73 : https://api.bilibili.com/x/web-interface/view?cid=192457764&bvid=BV1ff4y1176D
AbstractBaseParser-getAVDetail/74 :
AbstractBaseParser-getAVDetail/64 : https://api.bilibili.com/x/player/pagelist?bvid=BV18t4y117iP&jsonp=jsonp
AbstractBaseParser-getAVDetail/65 : {"code":0,"message":"0","ttl":1,"data":[{"cid":191273264,"page":1,"from":"vupload","part":"【血源诅咒】湊阿库娅的血源之旅 P6：拜伦维斯与亚哈古尔【剪辑熟肉】","duration":3252,"vid":"","weblink":"","dimension":{"width":1920,"height":1080,"rotate":0}}]}

发送GET请求出现异常！java.io.IOException: Server returned HTTP response code: 412 for URL: https://api.bilibili.com/x/web-interface/view?cid=191273264&bvid=BV18t4y117iP
java.io.IOException: Server returned HTTP response code: 412 for URL: https://api.bilibili.com/x/web-interface/view?cid=191273264&bvid=BV18t4y117iP
        at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at nicelee.bilibili.util.HttpRequestUtil.getContent(HttpRequestUtil.java:302)
        at nicelee.bilibili.parsers.impl.AbstractBaseParser.getAVDetail(AbstractBaseParser.java:72)
        at nicelee.bilibili.parsers.impl.URL4ChannelParser.convertVideoToClipMap(URL4ChannelParser.java:141)
        at nicelee.bilibili.parsers.impl.URL4ChannelParser.query(URL4ChannelParser.java:91)
        at nicelee.bilibili.parsers.impl.AbstractPageQueryParser.query(AbstractPageQueryParser.java:69)
        at nicelee.bilibili.parsers.impl.AbstractPageQueryParser.result(AbstractPageQueryParser.java:48)
        at nicelee.bilibili.parsers.impl.URL4ChannelParser.result(URL4ChannelParser.java:50)
        at nicelee.bilibili.parsers.InputParser.result(InputParser.java:89)
        at nicelee.bilibili.INeedAV.getVideoDetail(INeedAV.java:99)
        at nicelee.ui.thread.GetVideoDetailThread.run(GetVideoDetailThread.java:31)
Caused by: java.io.IOException: Server returned HTTP response code: 412 for URL: https://api.bilibili.com/x/web-interface/view?cid=191273264&bvid=BV18t4y117iP
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
        at java.net.URLConnection.getContentEncoding(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(Unknown Source)
        at nicelee.bilibili.util.HttpRequestUtil.getContent(HttpRequestUtil.java:301)
        ... 9 more
AbstractBaseParser-getAVDetail/73 : https://api.bilibili.com/x/web-interface/view?cid=191273264&bvid=BV18t4y117iP
AbstractBaseParser-getAVDetail/74 :`

关联视频页：https://space.bilibili.com/375504219/channel/detail?cid=99682

[![BBGDCd.png](https://s1.ax1x.com/2020/11/02/BBGDCd.png)](https://imgchr.com/i/BBGDCd)

**Comment by nICEnnnnnnnLee** [comment]
这可能是网络问题或者触发了bilibili风控。。。
请浏览器打开试试是不是正常反应
```
https://www.bilibili.com/video/BV18t4y117iP
https://space.bilibili.com/375504219/channel/detail?cid=99682
https://www.bilibili.com/blackboard/diagnostics.html
```

**Comment by HanakoLuna** [comment]
网络是正常的，三个网页都可以打开

[![BDA3xH.png](https://s1.ax1x.com/2020/11/02/BDA3xH.png)](https://imgchr.com/i/BDA3xH)

**Comment by nICEnnnnnnnLee** [comment]
请再使用程序试一试，估计是风控问题

**Comment by HanakoLuna** [comment]
好的，我今天再试试。
