### ISSUE TITLE
窗口关不掉？

### ISSUE THREAD

**Issue by lxfly2000** [nICEnnnnnnnLee/BilibiliDown#5]
报错`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException`
运行环境 OpenJDK 12.0.1

**Comment by nICEnnnnnnnLee** [comment]
+ 请问这个关闭窗口指的是？
     + 批量关闭Tab页 ![1](https://user-images.githubusercontent.com/19970934/56720078-8b278100-6774-11e9-88f9-cf8a55e00f3f.png)

     + 双击关闭Tab页 ![2](https://user-images.githubusercontent.com/19970934/56720091-97134300-6774-11e9-8381-d096ad35892f.png)

    + 还是退出程序![3](https://user-images.githubusercontent.com/19970934/56720102-9c708d80-6774-11e9-96a3-5a76bd4d82ae.png)

+ 另外，能描述一下出问题前的具体操作嘛，我看看能不能再复现😳

**Comment by lxfly2000** [comment]
就是退出程序，不需要任何其他操作

**Comment by nICEnnnnnnnLee** [comment]
很奇怪:confused: 想问一下：
+ 程序的其它功能是否正常？
+ 抛出异常时有没有更详细的信息。。。check了一下实在找不出问题在哪
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at xxx1.xxxx1.xxxxx1(xxxxx1.java:52)
    at xxx2.xxxx2.xxxxx2(xxxxx2.java:115)
    ...
```

**Comment by lxfly2000** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nicelee.bilibili.util.CmdUtil.deleteAllInactiveCmdTemp(CmdUtil.java:206)
        at nicelee.ui.FrameMain$1.windowClosing(FrameMain.java:113)
        at java.desktop/java.awt.Window.processWindowEvent(Window.java:2068)
        at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
        at java.desktop/java.awt.Window.processEvent(Window.java:2027)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by nICEnnnnnnnLee** [comment]
能看一下你的下载路径配置吗？ `bilibili.savePath`

应该是尝试删除临时文件，但没有找到下载文件夹😳

**Comment by nICEnnnnnnnLee** [comment]
我猜，在下了一个视频以后，现在你应该可以正常关闭了囧。
如果是这样，我知道问题在哪里了

**Comment by lxfly2000** [comment]
已经解决了，我新建了个download文件夹就好了。

**Comment by nICEnnnnnnnLee** [comment]
+ 这个问题[V3.2](https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/tag/V3.2)已经解决。
+ 没啥重大更新，嫌麻烦可以略过:smirk:
