### ISSUE TITLE
下载了比较多视频之后， 再点别的av就报这样的错误了

### ISSUE THREAD

**Issue by 447181567** [nICEnnnnnnnLee/BilibiliDown#50]
AbstractBaseParser-getAVDetail/64 : https://api.bilibili.com/x/player/pagelist?bvid=BV1Mb411e7SG&jsonp=jsonp
AbstractBaseParser-getAVDetail/65 : {"code":0,"message":"0","ttl":1,"data":[{"cid":80488141,"page":1,"from":"vupload","part":"吴青峰蜂鸟弹唱","duration":137,"vid":"","weblink":"","dimension":{"width":1920,"height":1080,"rotate":0}}]}

发送GET请求出现异常！java.io.IOException: Server returned HTTP response code: 412 for URL: https://api.bilibili.com/x/web-interface/view?cid=80488141&bvid=BV1Mb411e7SG
java.io.IOException: Server returned HTTP response code: 412 for URL: https://api.bilibili.com/x/web-interface/view?cid=80488141&bvid=BV1Mb411e7SG
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at nicelee.bilibili.util.HttpRequestUtil.getContent(HttpRequestUtil.java:302)
        at nicelee.bilibili.parsers.impl.AbstractBaseParser.getAVDetail(AbstractBaseParser.java:72)
        at nicelee.bilibili.parsers.impl.URL4UPAllParser.convertVideoToClipMap(URL4UPAllParser.java:120)
        at nicelee.bilibili.parsers.impl.URL4UPAllParser.query(URL4UPAllParser.java:98)
        at nicelee.bilibili.parsers.impl.AbstractPageQueryParser.query(AbstractPageQueryParser.java:69)
        at nicelee.bilibili.parsers.impl.AbstractPageQueryParser.result(AbstractPageQueryParser.java:48)
        at nicelee.bilibili.parsers.impl.URL4UPAllParser.result(URL4UPAllParser.java:53)
        at nicelee.bilibili.parsers.InputParser.result(InputParser.java:89)
        at nicelee.bilibili.INeedAV.getVideoDetail(INeedAV.java:99)
        at nicelee.ui.thread.GetVideoDetailThread.run(GetVideoDetailThread.java:31)
Caused by: java.io.IOException: Server returned HTTP response code: 412 for URL: https://api.bilibili.com/x/web-interface/view?cid=80488141&bvid=BV1Mb411e7SG
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
        at java.net.URLConnection.getContentEncoding(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(Unknown Source)
        at nicelee.bilibili.util.HttpRequestUtil.getContent(HttpRequestUtil.java:301)
        ... 9 more
AbstractBaseParser-getAVDetail/73 : https://api.bilibili.com/x/web-interface/view?cid=80488141&bvid=BV1Mb411e7SG
AbstractBaseParser-getAVDetail/74 :

**Comment by nICEnnnnnnnLee** [comment]
412是被风控了，需要等一段时间
