### ISSUE TITLE
protocol = http host = null

### ISSUE THREAD

**Issue by pluveto** [nICEnnnnnnnLee/BilibiliDown#65]
**我已经确认**
+ 使用的当前版本为最新版本
+ issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
protocol = http host = null

**相关信息**
+ 当前系统(windows/linux等)
+ java版本
+ 相关链接或者BV号
+ 账号是否登录
+ 在网页端观看是否存在问题
+ 是否存在自定义parsers
+ 相关log
  + windows下，运行run-UI-debug.bat，复现以后，复制一下控制台的输出
  + 其它平台，控制台cd到目录后java -Dfile.encoding=utf-8 -jar INeedBiliAV.jar，复现以后，复制一下控制台的输出

作者为 :未明子
作者ID为 :23191782
作者的话为 :
预览图路径为 :http://i1.hdslb.com/bfs/archive/9bb3a833f2e2cdd5d8e0229610b1640fc98e2eef.jpg
视频下载链接为 :null
当前有小视频个数 :1
------------------------------
--avTitle为 :【四十分钟哲学】哲学的二阶论域（3）：何为主体性
--page为 :1
--cId为 :327395945
--title为 :2021-04-21_23-26-41
--avId为 :BV1TK4y1P7gC
----下载链接 :
----下载链接 :
----下载链接 :
----下载链接 :
------------------------------
Uncaught error fetching image:
java.lang.IllegalArgumentException: protocol = http host = null
        at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:127)
        at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:263)
        at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
        at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)

**Comment by nICEnnnnnnnLee** [comment]
请确认是否是最新版本。该问题情况与#63 类似

**Comment by pluveto** [comment]
> 请确认是否是最新版本。该问题情况与#63 类似

是 6.2 版本

**Comment by pluveto** [comment]
可参考：https://github.com/jhy/jsoup/issues/932

**Comment by nICEnnnnnnnLee** [comment]
你在遇到这个问题时的链接或者BV号是什么？
问题能否稳定复现？

**Comment by pluveto** [comment]
链接：https://space.bilibili.com/23191782
在我的电脑上每次都可以复现。另外我还测试了一台 VPS（Windows Server 系统），在其上也能每次复现。

**Comment by nICEnnnnnnnLee** [comment]
+ 请检查一下是否存在自定义的parsers解析
+ 请检查一下封面的链接
![批注 2021-04-26 130352](https://user-images.githubusercontent.com/19970934/116031325-0091f900-a690-11eb-954c-9c12404acb3e.jpg)

```
理论上应该是：
http://i0.hdslb.com/bfs/archive/61f2128a0a572c6b9fcd0b5a63eee85e15fe9078.jpg
不应该是：
http:http://i0.hdslb.com/bfs/archive/61f2128a0a572c6b9fcd0b5a63eee85e15fe9078.jpg
```

**Comment by pluveto** [comment]
不存在你所圈出的按钮
![image](https://user-images.githubusercontent.com/50045289/116066591-cbe76700-a6ba-11eb-8810-a091fc21146d.png)

**Comment by nICEnnnnnnnLee** [comment]
+ 再确认一下，是否版本为v6.2且没有自定义parsers
+ 本来想图省事的，圈出来的那个是提示，单击加载中那个框可以复制链接到剪贴板

**Comment by pluveto** [comment]
破案了，重命名的时候看错了[捂脸]
![image](https://user-images.githubusercontent.com/50045289/116075873-13272500-a6c6-11eb-88b6-9e7f206e0d2b.png)
对不起，浪费了您的时间

**Comment by nICEnnnnnnnLee** [comment]
对于Windows用户，你可以在右上角菜单 `关于` -> `检查更新` 直接进行升级，从而避免出现此类问题。
