### ISSUE TITLE
视频下载成功但是偶尔有多余的txt文件出现

### ISSUE THREAD

**Issue by telessa** [nICEnnnnnnnLee/BilibiliDown#94]
**我已经确认**
 使用的当前版本为最新版本
issue区没有类似的情况

**问题描述**
目前只看到视频解析为flv 就有概率出现txt文件 虽然视频下载成功 但是出现大量的txt文件
这是提示什么错误吗？还是不用管 放心删了就行？
比如BV16s411V7sr-80-p1.flv.txt 
打开是
file 'BV16s411V7sr-80-p1-part1.flv'
file 'BV16s411V7sr-80-p1-part2.flv'
比如BV1z4411E7iJ-80-p1
log里解析为flv同样下载成功 但是没有出现txt
**相关信息**
+ 当前系统(windows/linux等)
Windows 10 21H2
+ java版本
(工作版本 1.8.0_321-b07)
+ 相关链接或者BV号
BV1z4411E7iJ BV16s411V7sr
+ 账号是否登录
是
+ 在网页端观看是否存在问题 
没有
+ 是否存在自定义parsers
否
+ 相关log
查询质量为:80的链接, 得到质量为:64的链接
发送GET请求出现异常！javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version
AbstractBaseParser-getVideoM4sLink/343 : 目标为FLV，切换解析方式
Exception in thread "pool-1-thread-34" org.json.JSONException: JSONObject["durl"] not found.
你点击了一次下载按钮...
查询记录BV1z4411E7iJ-80-p1
        at org.json.JSONObject.get(JSONObject.java:573)
        at org.json.JSONObject.getJSONArray(JSONObject.java:748)
        at nicelee.bilibili.parsers.impl.AbstractBaseParser.getVideoM4sLink(AbstractBaseParser.java:345)
        at nicelee.bilibili.parsers.impl.AbstractBaseParser.getVideoLink(AbstractBaseParser.java:218)
        at nicelee.bilibili.parsers.InputParser.getVideoLink(InputParser.java:100)
        at nicelee.ui.thread.DownloadRunnable.run(DownloadRunnable.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
已经下载过 BV1z4411E7iJ-80-p1

```
请在发表issue前进行预览，将影响排版的内容放到这里
```

**Comment by nICEnnnnnnnLee** [comment]
+ 出现txt未删除的情况，大概率对应的视频未能正确地下载完成。
+ 从提供的log看不出什么信息，只能看出HTTPS网络连接出现错误。

+ 需要提供的信息有以下配置以及相应log：
```
bilibili.flv.ffmpeg
bilibili.ffmpegPath
bilibili.savePath
```
(在抓取log前，可以先设置`bilibili.repo = off`关闭已下载查询)
